<?php

/**
 * V0.9 course-level learning analytics built from the local xAPI outbox.
 *
 * This repository is intentionally read-only. It does not modify outbox rows and
 * it does not call the LRS. It aggregates statements already generated by the
 * EventHook plugin for the resources contained in one ILIAS course.
 */
class ilIliasTraxEventBridgeCourseAnalyticsRepository
{
    public const OUTBOX_TABLE = 'evnt_evhk_itxeb_out';

    /** @var ilDBInterface|mixed */
    private $db;

    public function __construct()
    {
        if (isset($GLOBALS['DIC']) && method_exists($GLOBALS['DIC'], 'database')) {
            $this->db = $GLOBALS['DIC']->database();
        } elseif (isset($GLOBALS['ilDB'])) {
            $this->db = $GLOBALS['ilDB'];
        } else {
            throw new RuntimeException('ILIAS database object not available.');
        }
    }

    public function tableExists(): bool
    {
        return method_exists($this->db, 'tableExists') && $this->db->tableExists(self::OUTBOX_TABLE);
    }

    /**
     * @param array<string,mixed> $course
     * @return array<string,mixed>
     */
    public function buildForCourse(array $course, int $days = 30, int $limit = 3000): array
    {
        $days = max(1, min(365, $days));
        $limit = max(100, min(10000, $limit));
        $resources = is_array($course['resources'] ?? null) ? $course['resources'] : [];
        $resourcesByRef = $this->resourcesByRefId($resources);
        $resourceRefIds = array_keys($resourcesByRef);
        $sinceTs = time() - ($days * 86400);

        $dashboard = $this->emptyDashboard($course, $days, $resourcesByRef);
        if (!$this->tableExists() || count($resourceRefIds) === 0) {
            return $dashboard;
        }

        $rows = $this->findRowsForResourceRefs($resourceRefIds, $sinceTs, $limit);
        foreach ($rows as $row) {
            $item = $this->normalizeRow($row, $resourcesByRef);
            $this->addItemToDashboard($dashboard, $item);
        }

        return $this->finalizeDashboard($dashboard);
    }

    /**
     * @param array<int,array<string,mixed>> $resources
     * @return array<int,array<string,mixed>>
     */
    private function resourcesByRefId(array $resources): array
    {
        $result = [];
        foreach ($resources as $resource) {
            $refId = (int) ($resource['ref_id'] ?? 0);
            if ($refId > 0) {
                $result[$refId] = $resource;
            }
        }
        return $result;
    }

    /**
     * @param array<string,mixed> $course
     * @param array<int,array<string,mixed>> $resourcesByRef
     * @return array<string,mixed>
     */
    private function emptyDashboard(array $course, int $days, array $resourcesByRef): array
    {
        $byResource = [];
        foreach ($resourcesByRef as $refId => $resource) {
            $byResource[$refId] = $this->emptyResourceStats($resource);
        }

        return [
            'course_ref_id' => (int) ($course['course_ref_id'] ?? 0),
            'course_title' => (string) ($course['course_title'] ?? ''),
            'period_days' => $days,
            'summary' => [
                'total' => 0,
                'sent' => 0,
                'failed' => 0,
                'pending' => 0,
                'generated' => 0,
                'sending' => 0,
                'active_learners' => 0,
                'resources_total' => count($resourcesByRef),
                'resources_with_traces' => 0,
                'tests_attempted' => 0,
                'tests_passed' => 0,
                'tests_failed' => 0,
                'avg_score_raw' => null,
            ],
            'learners' => [],
            'score_sum' => 0.0,
            'score_count' => 0,
            'by_day' => [],
            'by_verb' => [],
            'by_status' => [
                'generated' => 0,
                'sending' => 0,
                'sent' => 0,
                'failed' => 0,
                'other' => 0,
            ],
            'by_resource' => $byResource,
            'expert_rows' => [],
        ];
    }

    /** @param array<string,mixed> $resource */
    private function emptyResourceStats(array $resource): array
    {
        return [
            'ref_id' => (int) ($resource['ref_id'] ?? 0),
            'obj_id' => (int) ($resource['obj_id'] ?? 0),
            'obj_type' => (string) ($resource['obj_type'] ?? ''),
            'resource_family' => (string) ($resource['resource_family'] ?? ''),
            'title' => (string) ($resource['title'] ?? ''),
            'path' => (string) ($resource['path'] ?? ''),
            'enabled' => !empty($resource['enabled']),
            'configured' => !empty($resource['configured']),
            'traces' => 0,
            'sent' => 0,
            'failed' => 0,
            'pending' => 0,
            'learners' => [],
            'learners_count' => 0,
            'last_ts' => 0,
            'last_at' => '',
            'verb_counts' => [],
            'spent_seconds_sum' => 0,
            'spent_seconds_count' => 0,
            'avg_spent_seconds' => null,
            'score_sum' => 0.0,
            'score_count' => 0,
            'avg_score_raw' => null,
            'test_attempts' => 0,
            'test_passed' => 0,
            'test_failed' => 0,
            'signal' => 'aucune trace',
        ];
    }

    /**
     * @param array<int,int> $refIds
     * @return array<int,array<string,mixed>>
     */
    private function findRowsForResourceRefs(array $refIds, int $sinceTs, int $limit): array
    {
        $refIds = array_values(array_unique(array_filter(array_map('intval', $refIds), static function (int $value): bool {
            return $value > 0;
        })));
        if (count($refIds) === 0) {
            return [];
        }

        $query = 'SELECT id, event_log_id, statement_uuid, event_type, verb_id, user_id, ref_id, obj_id, obj_type, '
            . 'statement_json, status, created_at, created_ts, sent_at, last_error, retry_count, max_retry, last_attempt_at '
            . 'FROM ' . self::OUTBOX_TABLE
            . ' WHERE ref_id IN (' . implode(',', $refIds) . ')'
            . ' AND created_ts >= ' . max(0, $sinceTs)
            . ' ORDER BY id DESC';

        if (method_exists($this->db, 'setLimit')) {
            $this->db->setLimit($limit);
        }

        $rows = [];
        $set = $this->db->query($query);
        $count = 0;
        while (($row = $this->db->fetchAssoc($set)) && $count < $limit) {
            if (is_array($row)) {
                $rows[] = $row;
                $count++;
            }
        }

        return $rows;
    }

    /**
     * @param array<string,mixed> $row
     * @param array<int,array<string,mixed>> $resourcesByRef
     * @return array<string,mixed>
     */
    private function normalizeRow(array $row, array $resourcesByRef): array
    {
        $statement = $this->decodeJson((string) ($row['statement_json'] ?? ''));
        $refId = (int) ($row['ref_id'] ?? 0);
        $resource = $resourcesByRef[$refId] ?? [];
        $verbId = (string) ($row['verb_id'] ?? '');
        if ($verbId === '') {
            $verbId = (string) ($statement['verb']['id'] ?? '');
        }

        $result = is_array($statement['result'] ?? null) ? $statement['result'] : [];
        $resultExtensions = is_array($result['extensions'] ?? null) ? $result['extensions'] : [];
        $context = is_array($statement['context'] ?? null) ? $statement['context'] : [];
        $contextExtensions = is_array($context['extensions'] ?? null) ? $context['extensions'] : [];

        $scoreRaw = null;
        if (isset($result['score']) && is_array($result['score']) && isset($result['score']['raw']) && is_numeric($result['score']['raw'])) {
            $scoreRaw = (float) $result['score']['raw'];
        } elseif (is_numeric($this->extensionValue($resultExtensions, '/ilias_percentage'))) {
            $scoreRaw = (float) $this->extensionValue($resultExtensions, '/ilias_percentage');
        }

        $spentSeconds = $this->numericOrNull($this->extensionValue($resultExtensions, '/spent_seconds'));
        if ($spentSeconds === null) {
            $spentSeconds = $this->durationToSeconds((string) ($result['duration'] ?? ''));
        }

        $createdTs = (int) ($row['created_ts'] ?? 0);
        if ($createdTs <= 0) {
            $createdTs = $this->parseTimestamp((string) ($row['created_at'] ?? ''));
        }

        $userId = (int) ($row['user_id'] ?? 0);
        $learnerKey = $userId > 0 ? 'usr:' . $userId : $this->actorKey($statement);

        return [
            'outbox_id' => (int) ($row['id'] ?? 0),
            'event_log_id' => (int) ($row['event_log_id'] ?? 0),
            'statement_uuid' => (string) ($row['statement_uuid'] ?? ($statement['id'] ?? '')),
            'event_type' => (string) ($row['event_type'] ?? $this->extensionValue($contextExtensions, '/source_event')),
            'statement_family' => (string) $this->extensionValue($contextExtensions, '/statement_family'),
            'interaction_type' => (string) $this->extensionValue($contextExtensions, '/interaction_type'),
            'verb_id' => $verbId,
            'verb_label' => $this->verbLabel($statement, $verbId),
            'user_id' => $userId,
            'learner_key' => $learnerKey,
            'ref_id' => $refId,
            'obj_id' => (int) ($row['obj_id'] ?? ($resource['obj_id'] ?? 0)),
            'obj_type' => (string) ($row['obj_type'] ?? ($resource['obj_type'] ?? '')),
            'object_title' => $this->objectTitle($statement, $resource, $contextExtensions),
            'status' => (string) ($row['status'] ?? ''),
            'created_at' => (string) ($row['created_at'] ?? ''),
            'created_ts' => $createdTs,
            'sent_at' => (string) ($row['sent_at'] ?? ''),
            'last_error' => (string) ($row['last_error'] ?? ''),
            'retry_count' => (int) ($row['retry_count'] ?? 0),
            'max_retry' => (int) ($row['max_retry'] ?? 0),
            'score_raw' => $scoreRaw,
            'completion' => isset($result['completion']) ? (bool) $result['completion'] : null,
            'success' => isset($result['success']) ? (bool) $result['success'] : null,
            'spent_seconds' => $spentSeconds,
            'read_count' => $this->numericOrNull($this->extensionValue($resultExtensions, '/read_count')),
        ];
    }

    /** @param array<string,mixed> $dashboard */
    private function addItemToDashboard(array &$dashboard, array $item): void
    {
        $dashboard['summary']['total']++;

        $status = (string) ($item['status'] ?? '');
        if (isset($dashboard['by_status'][$status])) {
            $dashboard['by_status'][$status]++;
        } else {
            $dashboard['by_status']['other']++;
        }

        if ($status === 'sent') {
            $dashboard['summary']['sent']++;
        } elseif ($status === 'failed') {
            $dashboard['summary']['failed']++;
        } elseif ($status === 'generated') {
            $dashboard['summary']['generated']++;
            $dashboard['summary']['pending']++;
        } elseif ($status === 'sending') {
            $dashboard['summary']['sending']++;
            $dashboard['summary']['pending']++;
        }

        $learnerKey = (string) ($item['learner_key'] ?? '');
        if ($learnerKey !== '') {
            $dashboard['learners'][$learnerKey] = true;
        }

        $day = $this->dayFromTimestamp((int) ($item['created_ts'] ?? 0));
        if (!isset($dashboard['by_day'][$day])) {
            $dashboard['by_day'][$day] = 0;
        }
        $dashboard['by_day'][$day]++;

        $verbKey = (string) ($item['verb_id'] ?? '');
        if ($verbKey === '') {
            $verbKey = 'unknown';
        }
        if (!isset($dashboard['by_verb'][$verbKey])) {
            $dashboard['by_verb'][$verbKey] = [
                'verb_id' => $verbKey,
                'label' => (string) ($item['verb_label'] ?? $verbKey),
                'count' => 0,
            ];
        }
        $dashboard['by_verb'][$verbKey]['count']++;

        $scoreRaw = $item['score_raw'];
        if (is_numeric($scoreRaw)) {
            $dashboard['score_sum'] += (float) $scoreRaw;
            $dashboard['score_count']++;
        }

        $objType = (string) ($item['obj_type'] ?? '');
        if ($objType === 'tst') {
            $dashboard['summary']['tests_attempted']++;
            if (($item['success'] ?? null) === true) {
                $dashboard['summary']['tests_passed']++;
            } elseif (($item['success'] ?? null) === false) {
                $dashboard['summary']['tests_failed']++;
            }
        }

        $refId = (int) ($item['ref_id'] ?? 0);
        if (isset($dashboard['by_resource'][$refId])) {
            $this->addItemToResourceStats($dashboard['by_resource'][$refId], $item);
        }

        if (count($dashboard['expert_rows']) < 200) {
            $dashboard['expert_rows'][] = $item;
        }
    }

    /** @param array<string,mixed> $stats */
    private function addItemToResourceStats(array &$stats, array $item): void
    {
        $stats['traces']++;
        $status = (string) ($item['status'] ?? '');
        if ($status === 'sent') {
            $stats['sent']++;
        } elseif ($status === 'failed') {
            $stats['failed']++;
        } elseif ($status === 'generated' || $status === 'sending') {
            $stats['pending']++;
        }

        $learnerKey = (string) ($item['learner_key'] ?? '');
        if ($learnerKey !== '') {
            $stats['learners'][$learnerKey] = true;
        }

        $createdTs = (int) ($item['created_ts'] ?? 0);
        if ($createdTs > (int) ($stats['last_ts'] ?? 0)) {
            $stats['last_ts'] = $createdTs;
            $stats['last_at'] = (string) ($item['created_at'] ?? '');
        }

        $verbLabel = (string) ($item['verb_label'] ?? '');
        if ($verbLabel !== '') {
            if (!isset($stats['verb_counts'][$verbLabel])) {
                $stats['verb_counts'][$verbLabel] = 0;
            }
            $stats['verb_counts'][$verbLabel]++;
        }

        $spent = $item['spent_seconds'];
        if (is_numeric($spent) && (int) $spent > 0) {
            $stats['spent_seconds_sum'] += (int) $spent;
            $stats['spent_seconds_count']++;
        }

        $scoreRaw = $item['score_raw'];
        if (is_numeric($scoreRaw)) {
            $stats['score_sum'] += (float) $scoreRaw;
            $stats['score_count']++;
        }

        if ((string) ($item['obj_type'] ?? '') === 'tst') {
            $stats['test_attempts']++;
            if (($item['success'] ?? null) === true) {
                $stats['test_passed']++;
            } elseif (($item['success'] ?? null) === false) {
                $stats['test_failed']++;
            }
        }
    }

    /** @param array<string,mixed> $dashboard */
    private function finalizeDashboard(array $dashboard): array
    {
        $dashboard['summary']['active_learners'] = count($dashboard['learners']);
        $dashboard['summary']['avg_score_raw'] = $dashboard['score_count'] > 0
            ? round($dashboard['score_sum'] / $dashboard['score_count'], 2)
            : null;

        ksort($dashboard['by_day']);
        uasort($dashboard['by_verb'], static function (array $left, array $right): int {
            return (int) ($right['count'] ?? 0) <=> (int) ($left['count'] ?? 0);
        });

        $resourcesWithTraces = 0;
        foreach ($dashboard['by_resource'] as $refId => $stats) {
            $stats['learners_count'] = count($stats['learners']);
            unset($stats['learners']);

            $stats['avg_spent_seconds'] = (int) ($stats['spent_seconds_count'] ?? 0) > 0
                ? (int) round((int) $stats['spent_seconds_sum'] / (int) $stats['spent_seconds_count'])
                : null;
            $stats['avg_score_raw'] = (int) ($stats['score_count'] ?? 0) > 0
                ? round((float) $stats['score_sum'] / (int) $stats['score_count'], 2)
                : null;

            $stats['signal'] = $this->resourceSignal($stats);
            if ((int) ($stats['traces'] ?? 0) > 0) {
                $resourcesWithTraces++;
            }
            $dashboard['by_resource'][$refId] = $stats;
        }
        $dashboard['summary']['resources_with_traces'] = $resourcesWithTraces;

        uasort($dashboard['by_resource'], static function (array $left, array $right): int {
            $traceCompare = (int) ($right['traces'] ?? 0) <=> (int) ($left['traces'] ?? 0);
            if ($traceCompare !== 0) {
                return $traceCompare;
            }
            return strcmp((string) ($left['title'] ?? ''), (string) ($right['title'] ?? ''));
        });

        unset($dashboard['learners'], $dashboard['score_sum'], $dashboard['score_count']);
        return $dashboard;
    }

    /** @param array<string,mixed> $stats */
    private function resourceSignal(array $stats): string
    {
        $traces = (int) ($stats['traces'] ?? 0);
        if ($traces === 0) {
            return !empty($stats['enabled']) ? 'activée sans trace' : 'non utilisée';
        }
        if ((int) ($stats['failed'] ?? 0) > 0) {
            return 'erreurs à vérifier';
        }
        if ((string) ($stats['obj_type'] ?? '') === 'tst' && (int) ($stats['test_failed'] ?? 0) > (int) ($stats['test_passed'] ?? 0)) {
            return 'test difficile';
        }
        if ($traces < 3) {
            return 'peu utilisée';
        }
        return 'utilisée';
    }

    /** @return array<string,mixed> */
    private function decodeJson(string $json): array
    {
        if (trim($json) === '') {
            return [];
        }
        $decoded = json_decode($json, true);
        return is_array($decoded) ? $decoded : [];
    }

    /** @param array<string,mixed> $statement */
    private function verbLabel(array $statement, string $verbId): string
    {
        $display = $statement['verb']['display'] ?? [];
        if (is_array($display)) {
            foreach (['fr-FR', 'fr', 'en-US', 'en'] as $locale) {
                if (isset($display[$locale]) && is_scalar($display[$locale]) && trim((string) $display[$locale]) !== '') {
                    return (string) $display[$locale];
                }
            }
        }
        if ($verbId !== '') {
            $parts = preg_split('/[\/#]/', $verbId);
            $last = is_array($parts) ? end($parts) : false;
            return is_string($last) && $last !== '' ? $last : $verbId;
        }
        return 'unknown';
    }

    /**
     * @param array<string,mixed> $statement
     * @param array<string,mixed> $resource
     * @param array<string,mixed> $contextExtensions
     */
    private function objectTitle(array $statement, array $resource, array $contextExtensions): string
    {
        $name = $statement['object']['definition']['name'] ?? [];
        if (is_array($name)) {
            foreach (['fr-FR', 'fr', 'en-US', 'en'] as $locale) {
                if (isset($name[$locale]) && is_scalar($name[$locale]) && trim((string) $name[$locale]) !== '') {
                    return (string) $name[$locale];
                }
            }
        }

        $extensionTitle = $this->extensionValue($contextExtensions, '/object_title');
        if (is_scalar($extensionTitle) && trim((string) $extensionTitle) !== '') {
            return (string) $extensionTitle;
        }

        $resourceTitle = (string) ($resource['title'] ?? '');
        if ($resourceTitle !== '') {
            return $resourceTitle;
        }

        return 'ref_id ' . (string) ($resource['ref_id'] ?? '');
    }

    /** @param array<string,mixed> $extensions */
    private function extensionValue(array $extensions, string $suffix)
    {
        foreach ($extensions as $key => $value) {
            if (is_string($key) && substr($key, -strlen($suffix)) === $suffix) {
                return $value;
            }
        }
        return null;
    }

    private function numericOrNull($value): ?float
    {
        return is_numeric($value) ? (float) $value : null;
    }

    private function durationToSeconds(string $duration): ?int
    {
        if ($duration === '' || strpos($duration, 'P') !== 0) {
            return null;
        }
        if (!preg_match('/^P(?:(\d+)D)?(?:T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+(?:\.\d+)?)S)?)?$/', $duration, $matches)) {
            return null;
        }

        $days = isset($matches[1]) && $matches[1] !== '' ? (int) $matches[1] : 0;
        $hours = isset($matches[2]) && $matches[2] !== '' ? (int) $matches[2] : 0;
        $minutes = isset($matches[3]) && $matches[3] !== '' ? (int) $matches[3] : 0;
        $seconds = isset($matches[4]) && $matches[4] !== '' ? (float) $matches[4] : 0.0;

        return (int) round(($days * 86400) + ($hours * 3600) + ($minutes * 60) + $seconds);
    }

    private function parseTimestamp(string $value): int
    {
        $ts = strtotime($value);
        return $ts === false ? 0 : (int) $ts;
    }

    private function dayFromTimestamp(int $timestamp): string
    {
        return $timestamp > 0 ? date('Y-m-d', $timestamp) : 'inconnue';
    }

    /** @param array<string,mixed> $statement */
    private function actorKey(array $statement): string
    {
        $accountName = $statement['actor']['account']['name'] ?? '';
        if (is_scalar($accountName) && trim((string) $accountName) !== '') {
            return 'actor:' . sha1((string) $accountName);
        }

        $mbox = $statement['actor']['mbox'] ?? '';
        if (is_scalar($mbox) && trim((string) $mbox) !== '') {
            return 'actor:' . sha1((string) $mbox);
        }

        return '';
    }
}
